### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by SheepCommander** [lorencerri/powercord-reverse-image-search#11]
![image](https://user-images.githubusercontent.com/66646514/148706629-87f1edcc-09b9-4468-addf-172c5048a6e5.png)

**Comment by lorencerri** [comment]
Hello, thank you for bringing this to my attention. It seems a recent Canary update broke the functionality of this and a few other plugins. I'll attempt to fix the plugin as soon as possible!

**Comment by SheepCommander** [comment]
Thanks!

**Comment by SheepCommander** [comment]
![image](https://user-images.githubusercontent.com/66646514/149249508-c63d67c6-3486-4208-9941-0e08e852632c.png)

**Comment by IveMalfunctioned** [comment]
Same issue here. I just used [this instead](https://github.com/powerfart-plugins/image-tools)

**Comment by lorencerri** [comment]
Recent updates seem to be working, no reports of improper functionality
