### ISSUE TITLE
Can't find image if through pop-out image

### ISSUE THREAD

**Issue by arsyadbruh** [lorencerri/powercord-reverse-image-search#9]
**Description**
plugin can't find image if we run from context menu on pop-out image. screenshot the search result :
![image](https://user-images.githubusercontent.com/71438511/134747849-bc0ef5e4-2c5c-4c41-8740-cd91cf69b531.png)
![image](https://user-images.githubusercontent.com/71438511/134747855-aa3f41d1-86ee-4ee2-b747-3b06f0e31e19.png)
google result is _The URL does not refer to an image, or the image must not be publicly accessible._

**To reproduce**

- Click image
- Right-click image pop-out
- Try searching the image (search engine it's up to you)

**Expected**
Search results that match the image

i sorry if my english is bad, i try without google translate.

**Comment by lorencerri** [comment]
Hello, I'm unfortunately unable to reproduce this issue. Is this happening to all images for you?

**Comment by lorencerri** [comment]
Hello, I was able to reproduce this issue and updated the code (396b211), thank you for the report!

*If the issue still is occurring, please reply to this message and I can do some more troubleshooting.*
